"""
Clarifying-questions service.

Before the agent runs, we ask the LLM to read the user's goal and produce
2-4 short clarifying questions (budget, brand, location, constraints...).
The user answers them in the UI; answers are appended to the task context
so the agent executes with less ambiguity.

Always returns a form: questions are generated by the task's own model
(Grok / OpenAI / Ollama). If that fails (no key, provider down, bad JSON,
timeout) we fall back to a generic question set so the user is always asked
to narrow the request before the agent runs.
"""

import json
import re

import httpx

from app.config import settings
from app.core.logging import get_logger
from app.schemas.task import ClarifyQuestion
from app.services.ollama_client import ollama_client

logger = get_logger(__name__)


def _is_grok(model: str) -> bool:
    return (model or "").lower().startswith("grok")


def _is_openai(model: str) -> bool:
    return (model or "").lower().startswith(("gpt", "chatgpt", "o1", "o3", "o4"))


# Shown whenever the model can't generate task-specific questions (no key, Ollama
# down, timeout, bad JSON). Guarantees the user always gets a form to narrow the
# request before the agent runs.
def _fallback_questions() -> list[ClarifyQuestion]:
    return [
        ClarifyQuestion(id=0, question="What's your budget or price range?", type="text",
                        options=[], placeholder="e.g. under $500, no limit"),
        ClarifyQuestion(id=1, question="Any preferred brands, websites, or sources?", type="text",
                        options=[], placeholder="e.g. Sony, official store, a specific site"),
        ClarifyQuestion(id=2, question="What matters most here?", type="text",
                        options=[], placeholder="e.g. quality, speed, reviews, lowest price"),
        ClarifyQuestion(id=3, question="How should I present the results?", type="choice",
                        options=["Best pick + alternatives", "Detailed comparison",
                                 "Just the single best", "Full list"]),
    ]


async def _generate_hosted(system: str, prompt: str, model: str, api_key: str, base_url: str) -> str:
    """Single-turn completion against an OpenAI-compatible endpoint (xAI / OpenAI)."""
    async with httpx.AsyncClient(timeout=30.0) as client:
        resp = await client.post(
            f"{base_url}/chat/completions",
            headers={"Authorization": f"Bearer {api_key}"},
            json={
                "model": model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
            },
        )
        resp.raise_for_status()
        data = resp.json()
        return (data.get("choices") or [{}])[0].get("message", {}).get("content", "") or ""

_SYSTEM = (
    "You prepare a browser automation agent for a task. "
    "Given the user's goal, ask ONLY the clarifying questions whose answers would "
    "change how the task is executed (budget, specific site, quantity, "
    "brand preference, dates, login needed, output format). "
    "Rules:\n"
    "- 2 to 4 questions maximum. Fewer is better.\n"
    "- Never ask about things already stated in the goal.\n"
    "- NEVER ask for the delivery address, pincode/ZIP, or payment method (UPI / card / "
    "cash on delivery): the user's saved shopping accounts already have the address, and "
    "the payment choice is handled later at checkout, not here.\n"
    "- Each question must be short (under 15 words).\n"
    "- Prefer multiple-choice when sensible (3-4 concise options).\n"
    "- If the goal is already fully specified, return an empty list.\n"
    'Respond with JSON only: {"questions": [{"question": "...", "type": "choice", '
    '"options": ["a", "b"]}, {"question": "...", "type": "text", "placeholder": "..."}]}'
)


def _parse_questions(raw: str) -> list[ClarifyQuestion]:
    """Parse the model output into ClarifyQuestion objects. Empty list on any failure."""
    if not raw or not raw.strip():
        return []

    text = raw.strip()
    # Strip markdown fences if the model added them despite JSON mode
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text)

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return []

    items = data.get("questions", []) if isinstance(data, dict) else []
    questions: list[ClarifyQuestion] = []

    for i, item in enumerate(items[:4]):
        if not isinstance(item, dict):
            continue
        q = str(item.get("question", "")).strip()
        if len(q) < 5:
            continue
        qtype = item.get("type", "text")
        options = [str(o).strip() for o in (item.get("options") or []) if str(o).strip()]
        if qtype == "choice" and len(options) < 2:
            qtype = "text"
        questions.append(
            ClarifyQuestion(
                id=i,
                question=q,
                type=qtype if qtype in ("text", "choice") else "text",
                options=options[:4] if qtype == "choice" else [],
                placeholder=(str(item.get("placeholder")).strip() or None)
                if item.get("placeholder")
                else None,
            )
        )
    return questions


async def generate_questions(
    goal: str, context: str | None, model: str, api_key: str | None = None
) -> list[ClarifyQuestion]:
    prompt = f"User goal: {goal}"
    if context:
        prompt += f"\n\nAlready-known context (do not ask about these):\n{context}"
    # We always want a form, so ask the model for at least 3 questions.
    prompt += "\n\nAsk 3-4 clarifying questions."

    raw = ""
    try:
        key = (api_key or "").strip()
        if _is_grok(model) and key:
            raw = await _generate_hosted(_SYSTEM, prompt, model, key, settings.XAI_BASE_URL)
        elif _is_openai(model) and key:
            raw = await _generate_hosted(_SYSTEM, prompt, model, key, settings.OPENAI_BASE_URL)
        elif not _is_grok(model) and not _is_openai(model):
            raw = await ollama_client.generate(
                prompt=prompt,
                model=model,
                system=_SYSTEM,
                temperature=0.3,
                format="json",
                think=False,  # thinking models return empty output with format=json otherwise
            )
    except Exception as exc:
        logger.warning("clarify_generation_failed", error=str(exc))
        raw = ""

    questions = _parse_questions(raw)
    # Always present a form: fall back to generic questions if the model gave
    # fewer than two (no key, provider down, or the goal looked unambiguous).
    if len(questions) < 2:
        questions = _fallback_questions()
        logger.info("clarify_questions_fallback", count=len(questions))
    else:
        logger.info("clarify_questions_generated", count=len(questions))
    return questions
